platform:
  - x86

branches:
  only:
    - master
    - develop

install:
  - cinst -y nsis
  - SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;%PATH%
  - ps: Expand-Archive -Path .\UAC.zip -Destination .\UAC
  - ps: Move-Item .\UAC\Plugins\x86-ansi\UAC.dll 'C:\Program Files (x86)\NSIS\Plugins\x86-ansi\UAC.dll'
  - ps: Move-Item .\UAC\Plugins\x86-unicode\UAC.dll 'C:\Program Files (x86)\NSIS\Plugins\x86-unicode\UAC.dll'
  - ps: Move-Item .\UAC\UAC.nsh 'C:\Program Files (x86)\NSIS\Include\UAC.nsh'

build_script:
- cmd: makensis build.nsi

artifacts:
  - path: .\*.exe
    name: QuirkbotDriverInstaller

version: "{build}"

skip_tags: true

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
